config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  get 'homes/index'
  resources :objectives, :rules
  resources :successes,only: [:index, :new, :create, :destroy]
  #resources :successes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '短期目標' },
    { id: 2, name: '中期目標' },
    { id: 3, name: '長期目標' },
    { id: 4, name: '指定なし' }
  ]
  include ActiveHash::Associations
  has_many :objectives
end

app/models/objective.rb
class Objective < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :category

  with_options presence: true do
    validates :title
    validates :category_id
    validates :wish
    validates :outcome
    validates :obstacle
    validates :plan
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :if_1
    validates :then_1
  end
end

app/models/success.rb
class Success < ApplicationRecord
  belongs_to :user

  NGWORD_REGEX = /(.)\1{4,}/.freeze
  with_options presence: true do  
   with_options format: { without: NGWORD_REGEX, message: 'は5文字以上の連続する文字は禁止です' } do
    validates :post, obscenity: { message: 'にNGワードが入力されています' }
   end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :objectives
  has_many :rules
  has_many :successes

  with_options presence: true do
    validates :nickname, length: { maximum: 10 }
    validates :birthday
    validates :email
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_objective, only: [:edit, :show, :destroy, :update]

  def index
    @objectives = current_user.objectives.all.order(created_at: :desc)
  end

  def new
    @objective = Objective.new
  end

  def create
    @objective = Objective.new(objective_params)
    if @objective.save
      redirect_to objectives_path
    else
      render :new
    end
  end

  def destroy
    @objective.destroy
  end

  def edit
  end

  def update
    @objective.update(objective_params)
  end

  def show
  end

  private

  def objective_params
    params.require(:objective).permit(:title, :category_id, :wish, :outcome, :obstacle, :plan).merge(user_id: current_user.id)
  end

  def set_objective
    @objective = current_user.objectives.find(params[:id])
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rule, only: [:edit, :show, :destroy, :update]

  def index
    @rules = current_user.rules.all.order(created_at: :desc)
  end

  def new
    @rule = Rule.new
  end

  def create
    @rule = Rule.new(rule_params)
    if @rule.save
      redirect_to rules_path
    else
      render :new
    end
  end

  def destroy
    @rule.destroy
  end

  def edit
  end

  def update
    @rule.update(rule_params)
  end

  def show
  end

  private

  def rule_params
    params.require(:rule).permit(:if_1, :then_1).merge(user_id: current_user.id)
  end

  def set_rule
    @rule = current_user.rules.find(params[:id])
  end
end

app/controllers/successes_controller.rb
class SuccessesController < ApplicationController
  before_action :authenticate_user!

  def index
    @successes = current_user.successes.all.order(created_at: :desc)
  end

  def new
    @success = Success.new
  end

  def create
    @success = Success.new(success_params)
    if @success.save
      redirect_to successes_path
    else
      render :new
    end
  end

  def destroy
    @success = current_user.successes.find(params[:id])
    @success.destroy
  end

  private

  def success_params
    params.require(:success).permit(:post).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/successes_helper.rb
module SuccessesHelper
end

app/views/homes/index.html.erb
<%= render "shared/header" %>
<!-- 後で実装 -->
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelEs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/objectives/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <%= link_to '投稿一覧へ戻る', objectives_path, class: "btn" %>
  </div>
</div> 

app/views/objectives/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
        <%= link_to '投稿一覧へ戻る', objectives_path, class: "btn" %>
  </div>
</div> 

app/views/objectives/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @objective, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :title, placeholder: "タイトル" %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <%= f.text_area :wish, placeholder: "（願望）簡単すぎず、難しすぎもしない。しかし重要であることを書く。", rows: "10" %>
      <%= f.text_area :outcome, placeholder: "（結果）それが叶った時の最高の結果を書く。", rows: "10" %>
      <%= f.text_area :obstacle, placeholder: "（障害）願望を叶えるために障害になりうることを書く。", rows: "10" %>
      <%= f.text_area :plan, placeholder: "（計画）上記、障害に対処する方法や回避する方法を書く。", rows: "10" %>
      <%= f.submit "更新する" %>
    <% end %>
  </div>
</div> 

app/views/objectives/index.html.erb
<div class="contents row">
<%= link_to '目標を作成する', new_objective_path, class: "login" %>
  <% @objectives.each do |objective| %>
    <div class="content_post" style="background-image: url(<%= asset_path('note.png') %>);"%>
      <div class="more">
        <span><%= image_tag 'menu.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', objective_path(objective.id), method: :get %>
          </li>
          <li>
            <%= link_to '編集', edit_objective_path(objective.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', objective_path(objective.id), method: :delete %>
          </li>
        </ul>
      </div>
      <div class="overview">
      <ul>
        <li class="overview_text_created_at"><%= objective.created_at.strftime('%Y/%m/%d') %>【<%= objective.category.name %>】</li>
        <br>
        <li class="overview_text"><%= link_to objective.title, objective_path(objective.id) %></li>
      </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/objectives/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>目標を作成する</h3>
    <%= form_with(model: @objective, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :title, placeholder: "タイトル" %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <%= f.text_area :wish, placeholder: "（願望）簡単すぎず、難しすぎもしない。しかし重要であることを書く。", rows: "10" %>
      <%= f.text_area :outcome, placeholder: "（結果）それが叶った時の最高の結果を書く。", rows: "10" %>
      <%= f.text_area :obstacle, placeholder: "（障害）願望を叶えるために障害になりうることを書く。", rows: "10" %>
      <%= f.text_area :plan, placeholder: "（計画）上記、障害に対処する方法や回避する方法を書く。", rows: "10" %>
      <%= f.submit "作成" %>
    <% end %>
  </div>
</div>

app/views/objectives/show.html.erb
<div class="contents row">
    <div class="content_post" style="background-image: url(<%= asset_path('note.png') %>);"%>
      <div class="more">
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_objective_path(@objective.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', objective_path(@objective.id), method: :delete %>
          </li>
        </ul>
      </div>
      <div >
        <ul class="objective-explain-box">
            <li><%= @objective.created_at.strftime('%Y/%m/%d') %>【<%= @objective.category.name %>】</li>
            <br><br>
            <li><b><%= @objective.title %></b></li>
            <br><br>
            <li>【願望（簡単すぎず難しすぎもしない。しかし重要であること。）】<br><%= safe_join(@objective.wish.split("\n"),tag(:br)) %></li>
            <br><br>
            <li>【結果（願望が叶った時の最高の結果による感情・状況・メリット）】<br><%= safe_join(@objective.outcome.split("\n"),tag(:br)) %></li>
            <br><br>
            <li>【障害（願望を叶えるために起こりうる障害）】<br><%= safe_join(@objective.obstacle.split("\n"),tag(:br)) %></li>
            <br><br>
            <li>【計画（障害に対する対処方法・回避方法）】<br><%= safe_join(@objective.plan.split("\n"),tag(:br)) %></li>
            <br><br>
        </ul>
      </div>
    </div>
</div>
<div class="contents row">
<div class="success">
  <%= link_to '目標一覧へ戻る', objectives_path, class: "btn" %>
</div>
</div>

app/views/objectives/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
        <%= link_to '投稿一覧へ戻る', objectives_path, class: "btn" %>
  </div>
</div> 

app/views/rules/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <%= link_to '投稿一覧へ戻る', rules_path, class: "btn" %>
  </div>
</div> 

app/views/rules/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
        <%= link_to '投稿一覧へ戻る', rules_path, class: "btn" %>
  </div>
</div> 

app/views/rules/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @rule, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :if_1, placeholder: "（状況）◯◯が起こったら", rows: "10" %>
      <%= f.text_area :then_1, placeholder: "（行動）◯◯をする", rows: "10" %>
      <%= f.submit "更新する" %>
    <% end %>
  </div>
</div> 

app/views/rules/index.html.erb
<div class="contents row">
<%= link_to '「習慣」if then プランニングを作成する', new_rule_path, class: "login" %>
  <% @rules.each do |rule| %>
    <div class="content_post" style="background-image: url(<%= asset_path('if.png') %>);"%>
      <div class="more">
        <span><%= image_tag 'menu.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', rule_path(rule.id), method: :get %>
          </li>
          <li>
            <%= link_to '編集', edit_rule_path(rule.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', rule_path(rule.id), method: :delete %>
          </li>
        </ul>
      </div>
      <div class="overview">
      <ul>
        <li class="overview_text_created_at"><%= rule.created_at.strftime('%Y/%m/%d') %>
        <br>
        <li class="overview_text"><%= link_to rule.if_1, rule_path(rule.id) %></li>
        <br>
        <li class="overview_text"><%= link_to rule.then_1, rule_path(rule.id) %></li>
      </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/rules/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>「習慣」if then プランニングを作成する</h3>
    <%= form_with(model: @rule, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :if_1, placeholder: "（状況）◯◯が起きたら", rows: "10" %>
      <%= f.text_area :then_1, placeholder: "（行動）◯◯をする", rows: "10" %>
      <%= f.submit "作成" %>
    <% end %>
  </div>
</div>

app/views/rules/show.html.erb
<div class="contents row">
    <div class="content_post" style="background-image: url(<%= asset_path('if.png') %>);"%>
      <div class="more">
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_rule_path(@rule.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', rule_path(@rule.id), method: :delete %>
          </li>
        </ul>
      </div>
      <div >
        <ul class="objective-explain-box">
            <li><%= @rule.created_at.strftime('%Y/%m/%d') %></li>
            <br><br>
            <li>【状況（時間と場所を中心に、できる限り具体的に設定）】<br><%= safe_join(@rule.if_1.split("\n"),tag(:br)) %></li>
            <br><br>
            <li>【行動（場面をイメージした上で、詳細まで具体的に設定）】<br><%= safe_join(@rule.then_1.split("\n"),tag(:br)) %></li>
            <br><br>
        </ul>
      </div>
    </div>
</div>
<div class="contents row">
<div class="success">
  <%= link_to '習慣一覧へ戻る', rules_path, class: "btn" %>
</div>
</div>

app/views/rules/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
        <%= link_to '習慣一覧へ戻る', rule_path, class: "btn" %>
  </div>
</div> 

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
    <div class='image-details'>
    <%= link_to image_tag("icon.png", class:"action-icon"), "/" %>
    </div>
    <nav class='footer-contents'>
     <p>© Copyright 2022 Seles All rights reserved.</p>
    </nav>
</div>

app/views/shared/_header.html.erb
<header class='top_page_header'>
    <div class='left_menu'>
    <%= link_to image_tag("icon.png", class:"seles-icon"), "/" %>
    </div>
    <div class='right_menu'>
      <ul>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, objectives_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      </ul>
    </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("icon.png", class:"second-logo"), "/" %>
</header>

app/views/successes/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <%= link_to '投稿一覧へ戻る', successes_path, class: "btn" %>
  </div>
</div> 

app/views/successes/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <%= link_to '投稿一覧へ戻る', successes_path, class: "btn" %>
  </div>
</div> 

app/views/successes/index.html.erb
<div class="contents row">
<%= link_to '成功体験を投稿する', new_success_path, class: "login" %>
  <% @successes.each do |success| %>
    <div class="content_post" style="background-image: url(<%= asset_path('success.png') %>);"%>
      <div class="more">
        <span><%= image_tag 'menu.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '削除', success_path(success.id), method: :delete %>
          </li>
        </ul>
      </div>
      <div class="overview">
      <ul>
        <li class="overview_text_created_at"><%= success.created_at.strftime('%Y/%m/%d') %>
        <br>
        <li class="overview_text"><%= success.post %></li>
        <br>
      </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/successes/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>成功体験を投稿する</h3>
    <%= form_with(model: @success, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :post, placeholder: "（成功体験）◯◯ができた等", rows: "10" %>
      <%= f.submit "投稿する" , id: "submit" %>
    <% end %>
  </div>
</div>